[package]
description = "Google Fonts subset definitions"
repository = "https://github.com/googlefonts/nam-files"
license-file = "LICENSE"
name = "google-fonts-subsets"
version = "0.202511.4"
edition = "2021"

[build-dependencies]
glob = "0.3"

[dependencies]
